### ISSUE TITLE
Errors during Wifi Config AP

### ISSUE THREAD

**Issue by 4m1g0** [G4lile0/ESP32-OLED-Fossa-GroundStation#4]
Sometimes config is not properly saved after sending the data though the config page and AP is launched again.

**Comment by nmaas87** [comment]
In addition, I can find to other potential problems at the same area:
- If saving with a wrong TZ, no time is shown. Maybe there would be a nice way to test the parameter before rebooting
- If opening up the page in i.e. Chrome on a system with german locale, the Latitude/Longitude will be shown with , instead of . - saving both parameters with , will result in it not working correctly (only got a hanging with black screen in the initial version of this GroundStation, maybe a hint like the text for the TZ would be good to ensure the parameter is entered in the correct way)
